// Generated by delombok at Sun Oct 18 18:13:47 CEST 2015
package fr.mby.commgr.projection;

import org.springframework.data.rest.core.config.Projection;

import fr.mby.commgr.domain.Community;

@Projection(name = "communityBase", types = { Community.class })
public interface CommunityBase {

	String getName();

	String getDescription();

	String getEmail();

	String getNote();

	boolean isJoinable();

	boolean isHidden();

}